### ISSUE TITLE
[OpenGothic] Outdated phoenix dependency

### ISSUE THREAD

**Issue by lmichaelis** [CReimer/PKGBUILDs#1]
Hey there, I just noticed that the *phoenix*-related dependencies listed in the PKGBUILD are outdated. *lexy* is no longer required to build phoenix as of version 1.1.1 which is the version OpenGothic 1.0.2207 depends on. Additionally, `lmichaelis/phoenix` has been moved to `GothicKit/phoenix`, so you should update the URL :)

**Comment by CReimer** [comment]
Fixed with 7d5c9543b3faa55f818e24df4cbdd300fcb84547. Thanks
